const scenes={
architecture:{name:'架构图',question:'由什么组成？',kicker:'01 / STRUCTURE',title:'从外部作者，到交互查看器',description:'11 个组件串起 Archify 的核心边界：作者提供图规格，程序负责生成、验收与交付。',read:'从左上方沿主链顺时针阅读。Skill 指导外部作者；仓库证据核验是加载阶段的可选分支。',boundary:'这是核心职责与处理链的抽象，未逐个展开所有脚本。架构节点中的“来源”可打开固定提交的代码。'},
workflow:{name:'工作流',question:'谁先做什么？',kicker:'02 / PROCESS',title:'一次 deliver：成功交付与失败重试',description:'按用户 / Agent、交付命令、渲染与检查三个泳道，观察职责如何交接。',read:'沿准备、生成与验收、交付三阶段向右读；红色分支把渲染或检查失败交回作者修改。',boundary:'修复由用户或 Agent 执行，Archify 不会自行让大模型重写规格。此图重点是职责与分支。'},
sequence:{name:'时序图',question:'调用怎样往返？',kicker:'03 / INTERACTION',title:'主进程、两个子进程与文件系统',description:'跟踪一次成功调用：冻结规格、运行渲染器、运行检查器、计算哈希，最后替换产物。',read:'时间从上往下；实线表示请求或写入，返回线表示读取结果或完成通知，细竖条表示参与者工作的区间。',boundary:'只画成功分支，并按可读粒度合并内部步骤。不是运行时抓取的性能追踪，没有真实耗时含义。'},
dataflow:{name:'数据流',question:'数据变成什么？',kicker:'04 / DATA',title:'一份 JSON 的几次形态变化',description:'图规格变成冻结快照、已校验对象、候选网页、最终网页；模板、证据与回执走各自支路。',read:'中间一行是主数据路径。上方资源进入候选网页，下方列出可选证据、交付回执和浏览器导出。',boundary:'这里的 IR 是图规格，不是代码 AST。源码关系已经由作者写进 JSON，渲染器不会自动补齐它。'},
lifecycle:{name:'生命周期',question:'如何完成或失败？',kicker:'05 / LIFECYCLE',title:'候选产物通过验收，才成为最终文件',description:'上方是正常阶段，下方是渲染、检查、提交失败时的结束路径。',read:'按主轨道五阶段阅读。失败分支最终清理候选；存在旧产物时，提交前失败保留旧文件。',boundary:'中文状态是根据 deliver 控制分支整理的阶段名，并非源码状态枚举。预览服务另有 checking / verified / needs-fix 状态。'},
delta:{name:'架构差异',question:'这次改了什么？',kicker:'06 / REAL CHANGE',title:'真实提交：在线字体 → 内嵌字体',description:'比较相邻提交 b86b607 → 1072200。一个外部字体依赖被移除，一个内嵌资源被加入，模板内容随之变化。',read:'Before 看改动前，Delta 看新增 / 删除 / 修改，After 看改动后。顶部 2 个新增、2 个删除分别包括节点与连线。',boundary:'两个快照来自本次代码分析，使用同一当前渲染器生成。比较器只比较声明的模型，不自动读取 Git diff 或推断影响。'}
};
const $=id=>document.getElementById(id);let active='architecture';const tabs=document.querySelector('.tabs');
Object.entries(scenes).forEach(([id,s],i)=>{const b=document.createElement('button');b.type='button';b.id='tab-'+id;b.role='tab';b.innerHTML='<b>'+s.name+'</b><small>'+s.question+'</small>';b.setAttribute('aria-controls','diagram');b.addEventListener('click',()=>select(id));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const ids=Object.keys(scenes);const n=e.key==='Home'?0:e.key==='End'?5:(i+(e.key==='ArrowRight'?1:5))%6;select(ids[n]);$('tab-'+ids[n]).focus();});tabs.append(b);});
function select(id,fragment='',scroll=false){if(!scenes[id])id='architecture';active=id;const s=scenes[id];for(const key of ['kicker','title','description','read','boundary'])$(key).textContent=s[key];const url='./diagrams/self-'+id+'.html'+(fragment?'#'+fragment:'');$('diagram').src=url;$('diagram').title='Archify '+s.name+'：'+s.title;$('open').href=url;$('mobile-open').href=url;$('mobile-image').src='./assets/self-'+id+'-preview.png';$('mobile-image').alt=s.title+'中文预览';$('spec').href='./specs/self-'+id+(id==='delta'?'-head':'')+'.json';$('receipt').href='./receipts/self-'+id+'.json';$('extra').hidden=id!=='delta';$('extra').href='./specs/self-delta-base.json';for(const key of Object.keys(scenes)){const b=$('tab-'+key);b.setAttribute('aria-selected',String(key===id));b.tabIndex=key===id?0:-1;}history.replaceState(null,'','#'+id);if(scroll)$('diagrams').scrollIntoView({behavior:'smooth'});}
document.querySelectorAll('[data-explore]').forEach(b=>b.addEventListener('click',()=>select('architecture',b.dataset.explore,true)));
function style(){const preset=$('preset').value,theme=$('theme').value;$('style-image').src='./assets/self-style-'+preset+'-'+theme+'.png';$('style-image').alt=preset+' '+(theme==='light'?'浅色':'深色')+'原生效果';}$('preset').addEventListener('change',style);$('theme').addEventListener('change',style);
let experiment;function phase(i){const s=experiment.states[i];$('preview-status').textContent=s.status+' · revision '+s.revision;$('preview-title').textContent=['第一版通过验收','输入无效，但第一版保留','修复输入后交付第二版'][i];$('preview-note').textContent=['服务完成初次生成，记录产物哈希。','注意：此处哈希与第一步完全相同，版本号也没有增加。','只有修复后的新候选通过检查，哈希和版本号才一起变化。'][i];$('preview-hash').textContent='SHA-256  '+s.artifactSha256;document.querySelectorAll('[data-phase]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.phase)===i);b.setAttribute('aria-pressed',String(Number(b.dataset.phase)===i));});}
fetch('./receipts/self-preview.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(r=>{experiment=r;phase(0);document.querySelectorAll('[data-phase]').forEach(b=>b.addEventListener('click',()=>phase(Number(b.dataset.phase))));}).catch(()=>{$('preview-status').textContent='记录加载失败，请打开下方原始记录。';});
const commit='10722002bb8777ecb639d93c49586fae4adf3ae4';const link=(p,line,end,label)=>'<a target="_blank" rel="noopener" href="https://github.com/tt-a1i/archify/blob/'+commit+'/archify/'+p+'#L'+line+'-L'+end+'">'+label+' ↗</a>';
const evidence=[['架构图',link('renderers/shared/cli.mjs',18,72,'加载、校验、组装')+link('renderers/architecture/render-architecture.mjs',1037,1078,'专用渲染器'),'核心职责与可选仓库证据边界'],['工作流',link('bin/archify.mjs',821,1189,'commandDeliver'),'冻结输入、验收、原子替换与失败返回'],['时序图',link('bin/archify.mjs',966,1176,'渲染子进程、检查子进程与文件交付'),'按代码控制顺序整理的成功调用序列'],['数据流',link('renderers/shared/cli.mjs',18,72,'图规格与资源载入')+link('renderers/shared/utils.mjs',126,175,'模板填充'),'规格、SVG、HTML、检查与哈希的流转'],['生命周期',link('bin/archify.mjs',966,1189,'失败分支与 finally 清理'),'提交前失败与成功交付的不同终点'],['实时预览',link('bin/preview.mjs',406,480,'publishFailure 与 commitCandidate'),'失败保留旧产物，通过检查再更新'],['真实变更','<a target="_blank" rel="noopener" href="https://github.com/tt-a1i/archify/commit/'+commit+'">完整提交差异 ↗</a>'+link('assets/template.html',34,55,'内嵌字体'),'在线字体依赖改为随 HTML 交付的资源']];$('evidence-rows').innerHTML=evidence.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('');
const initial=location.hash.slice(1);select(scenes[initial]?initial:'architecture');if(initial&&!scenes[initial]){history.replaceState(null,'','#'+initial);requestAnimationFrame(() => $(initial)?.scrollIntoView());}
