'use strict';
const types=['architecture','workflow','sequence','dataflow','lifecycle','delta'];
const kind=['架构图','工作流','时序图','数据流','生命周期','架构差异'];
const originals=[['Web 应用架构','入口、负载均衡、API、数据库、缓存与异步任务，展示系统组件和部署边界。'],['Agent 工具调用','按职责泳道展示规划、审批、工具执行、阻止与重试，以及证据回传。'],['缓存未命中的请求','请求经认证和缓存查询，再回退数据库，写缓存并返回响应。'],['产品分析数据流','从客户端事件采集，到敏感数据处理、仓库、指标与机器学习特征。'],['Agent 任务生命周期','正常阶段、审批等待、恢复循环，以及取消和过期等终止出口。'],['结算平台架构改造','使用上游提供的前后两份规格，演示新增、删除、修改、移动和改道。']];
const ours=[['从外部作者到交互查看器','11 个组件串起图规格、加载校验、专用渲染器、产物检查、原子交付与查看器。'],['一次 deliver 怎样完成','按用户／Agent、交付命令、渲染与检查三个泳道，说明成功和失败重试的职责。'],['主进程与两个子进程','沿实际控制顺序描述冻结输入、渲染、检查、哈希和替换；不表达真实耗时。'],['JSON 怎样成为网页','规格、冻结快照、已校验对象、SVG／HTML 的形态变化，以及证据和回执支路。'],['候选产物怎样走到终点','准备、生成、验收、提交与完成；提交前失败清理候选并保留已有最终文件。'],['真实变更：字体内嵌','分析相邻源码提交，整理在线字体依赖到内嵌资源的两个架构快照。']];
const labels={repository:'我们的研究仓库：从收录到网页'};
function populate(target,rows,prefix){const root=document.getElementById(target);rows.forEach(([title,description],i)=>{const type=types[i],id=prefix+type;labels[id]=title;const article=document.createElement('article');article.className='diagram-card';article.innerHTML=`<button class="image-button" data-diagram="${id}" aria-label="打开${title}"><img src="./assets/${id}-preview.png" loading="lazy" alt="${title}完整图形预览"></button><div class="diagram-copy"><span class="kind">${String(i+1).padStart(2,'0')} / ${kind[i]}</span><h3>${title}</h3><p>${description}</p><div class="card-links"><button class="text-button" data-diagram="${id}">打开交互图 ↗</button><a href="./specs/${id}${type==='delta'?'-head':''}.json" target="_blank" rel="noopener">图规格</a><a href="./receipts/${id}.json" target="_blank" rel="noopener">生成记录</a></div></div>`;root.append(article);});}
populate('upstream-gallery',originals,'');populate('self-gallery',ours,'self-');
const dialog=document.getElementById('viewer'),frame=document.getElementById('viewer-frame');let opener;
document.addEventListener('click',e=>{const button=e.target.closest('[data-diagram]');if(!button)return;opener=button;const id=button.dataset.diagram;if(!labels[id])return;const url='./diagrams/'+id+'.html'+(button.dataset.fragment?'#'+button.dataset.fragment:'');document.getElementById('viewer-title').textContent=labels[id];document.getElementById('viewer-open').href=url;frame.title=labels[id];frame.src=url;dialog.showModal();document.getElementById('viewer-close').focus();});
function closeViewer(){frame.src='about:blank';dialog.close();opener?.focus({preventScroll:true});}document.getElementById('viewer-close').addEventListener('click',closeViewer);dialog.addEventListener('cancel',e=>{e.preventDefault();closeViewer();});
function style(){const preset=document.getElementById('style-preset').value,theme=document.getElementById('style-theme').value;const img=document.getElementById('style-preview');img.src='./assets/self-style-'+preset+'-'+theme+'.png';img.alt=preset+' '+(theme==='light'?'浅色':'深色')+'主题实测截图';}document.getElementById('style-preset').addEventListener('change',style);document.getElementById('style-theme').addEventListener('change',style);
let proof;function phase(i){const s=proof.states[i];document.getElementById('proof-label').textContent=s.status+' · 第 '+s.revision+' 版';document.getElementById('proof-note').textContent=['第一版通过验收，记录成功产物的哈希。','故意损坏输入；此处哈希和版本号与第一步完全相同。','修复输入后重新验收，成功产物的哈希和版本一起更新。'][i];document.getElementById('proof-hash').textContent='SHA-256 '+s.artifactSha256;document.querySelectorAll('[data-phase]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.phase)===i)));}
fetch('./receipts/self-preview.json').then(r=>{if(!r.ok)throw Error('Record unavailable');return r.json();}).then(r=>{proof=r;phase(0);document.querySelectorAll('[data-phase]').forEach(b=>b.addEventListener('click',()=>phase(Number(b.dataset.phase))));}).catch(()=>{document.getElementById('proof-label').textContent='实测记录暂未载入，请通过左侧链接查看原始记录。';});
