import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
const project=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const upstream=path.resolve(project,'../../.research/archify');
const web=path.join(project,'web');
const revision='10722002bb8777ecb639d93c49586fae4adf3ae4';
const before='b86b60789e18829885dd23c844e36549f0b40303';
const git=spawnSync('git',['-C',upstream,'rev-parse','HEAD'],{encoding:'utf8'});
if(git.stdout.trim()!==revision)throw Error('Pinned Archify checkout required');
const source=(p,line,end_line,label)=>({path:'archify/'+p,line,end_line,label});
const meta=title=>({title,locale:'zh-CN',animation:'trace',quality_profile:'showcase',visual_preset:'signal-flow'});
const card=(title,text,dot='emerald')=>({title,dot,items:[text]});
const view=(id,label,focus,note)=>({id,label,focus,note});
const sources={
 skill:source('SKILL.md',1,45,'Agent 使用与表达规范'),
 cli:source('bin/archify.mjs',821,966,'deliver：读取与冻结规格'),
 loader:source('renderers/shared/cli.mjs',18,47,'加载、校验与资源读取'),
 evidence:source('renderers/shared/repository-evidence.mjs',74,140,'固定版本的文件与行号核验'),
 renderer:source('renderers/architecture/render-architecture.mjs',1037,1078,'架构 SVG 渲染与输出'),
 template:source('renderers/shared/utils.mjs',126,175,'把图与元数据装入模板'),
 checker:source('bin/archify.mjs',985,1034,'运行产物检查器'),
 commit:source('bin/archify.mjs',1074,1189,'哈希回执、原子替换与清理'),
 viewer:source('assets/template.html',12910,12965,'查看器中的有向路径查询'),
};
function component(id,type,label,sublabel,col,row,tag=''){return {id,type,label,sublabel,tag,pos:[40+col*300,30+row*180],size:[200,88],...(sources[id]?{sources:[sources[id]]}:{})};}
function edge(from,to,extra={}){return {id:from+'-'+to,from,to,...extra};}
const architecture={schema_version:1,diagram_type:'architecture',meta:{...meta('Archify：从图规格到交付'),repository:{url:'https://github.com/tt-a1i/archify',revision},views:[view('author','① 内容从哪里来',['agent','skill','spec'],'Agent 阅读代码并编写规格；Skill 约束表达。这里没有自动代码关系抽取器。'),view('deliver','② 生成与验收',['cli','loader','renderer','template','checker','commit'],'冻结输入，在私有目录生成候选；通过检查后才替换最终文件。'),view('read','③ 带证据阅读',['evidence','viewer'],'可选源代码核验检查版本、路径、行号；查看器沿规格中的关系探索。')],legend:{mode:'auto',entries:{external:{label:'外部作者'},database:{label:'规格与规范'},backend:{label:'程序模块'},security:{label:'校验环节'},frontend:{label:'浏览器界面'}}}},components:[component('agent','external','用户 / Agent','分析源码 · 决定表达',0,0),component('spec','database','五类 JSON 规格','节点 · 关系 · 布局',1,0,'结构化输入'),component('cli','backend','交付命令','冻结输入 · 调度子进程',2,0,'deliver'),component('loader','security','加载与校验','Schema · 引用 · 语义',3,0),component('skill','database','绘图 Skill','指导外部 Agent 写规格',0,1),component('evidence','security','仓库证据核验','可选 Git 版本与行范围',2,1),component('renderer','backend','五类专用渲染器','计算布局 · 生成 SVG',3,1),component('viewer','frontend','交互查看器','搜索 · 路径 · 导出',0,2),component('commit','backend','原子交付','哈希回执 · 替换文件',1,2),component('checker','security','产物检查器','结构与构图九项检查',2,2),component('template','backend','HTML 模板组装','嵌入图形 · 样式 · 脚本',3,2)],connections:[edge('agent','spec'),edge('spec','cli'),edge('cli','loader'),edge('loader','renderer',{fromSide:'bottom',toSide:'top'}),edge('renderer','template',{fromSide:'bottom',toSide:'top'}),edge('template','checker',{fromSide:'left',toSide:'right'}),edge('checker','commit',{fromSide:'left',toSide:'right'}),edge('commit','viewer',{fromSide:'left',toSide:'right'}),edge('skill','agent',{fromSide:'top',toSide:'bottom',variant:'dashed'}),edge('loader','evidence',{fromSide:'bottom',toSide:'right',variant:'security'})],cards:[card('信息来源','关系由本次源码分析后编写；Archify 负责校验和绘图。'),card('箭头含义','主链表示处理与交付顺序；证据核验是可选调用。'),card('证据边界','点选节点查看固定提交源码；引用有效不等于语义被证明。','rose')]};
const wn=(id,lane,col,type,label,sublabel)=>({id,lane,col,type,label,sublabel,width:142});
const workflow={schema_version:2,diagram_type:'workflow',meta:meta('Archify：一次交付怎样完成'),lanes:[{id:'author',label:'用户 / Agent'},{id:'cli',label:'交付命令'},{id:'engine',label:'渲染与检查'}],phases:[{id:'prepare',label:'准备',fromCol:0,toCol:1},{id:'generate',label:'生成与验收',fromCol:2,toCol:3,variant:'emphasis'},{id:'publish',label:'交付',fromCol:4,toCol:5}],mainPath:['input','freeze','render','check','commit','receipt'],nodes:[wn('input','author',0,'external','编写规格','确定内容与关系'),wn('freeze','cli',1,'backend','冻结快照','固定本次输入'),wn('render','engine',2,'backend','校验渲染','生成候选 HTML'),wn('check','engine',3,'security','检查候选','九项产物检查'),wn('commit','cli',4,'backend','原子提交','替换最终文件'),wn('receipt','cli',5,'database','返回回执','哈希与检查结果'),wn('repair','author',3,'external','修改后重试','由用户或 Agent 处理')],edges:[edge('input','freeze'),edge('freeze','render'),edge('render','check'),edge('check','commit'),edge('commit','receipt'),edge('check','repair',{role:'error',variant:'security',label:'失败',fromSide:'top',toSide:'bottom'}),edge('render','repair',{role:'error',variant:'security',fromSide:'top',toSide:'left'}),edge('repair','input',{role:'branch',variant:'dashed',fromSide:'left',toSide:'right'})],cards:[card('成功路径','快照 → 渲染 → 检查 → 原子替换；回执包含 SHA-256。'),card('失败路径','错误返回诊断；修改规格与重新调用由外部完成。','rose')]};
const steps=[['author','cli','调用 deliver'],['cli','disk','读取 JSON'],['disk','cli','原始字节','return'],['cli','disk','写入私有快照'],['cli','renderer','启动渲染子进程'],['renderer','disk','读取快照与模板'],['renderer','disk','写候选 HTML'],['renderer','cli','渲染成功','return'],['cli','checker','启动产物检查'],['checker','disk','读取候选 HTML'],['checker','cli','检查通过','return'],['cli','disk','读取产物算哈希'],['cli','disk','原子替换最终文件'],['cli','author','返回交付回执','return']];
const sequence={schema_version:1,diagram_type:'sequence',meta:{...meta('Archify：交付命令的进程时序'),viewBox:[1080,650],column_fit:'spread'},participants:[['author','external','调用者','用户 / Agent'],['cli','backend','交付命令','主进程'],['disk','database','文件系统','快照与产物'],['renderer','backend','渲染器','子进程'],['checker','security','检查器','子进程']].map(([id,type,label,sublabel])=>({id,type,label,sublabel})),segments:[{from:150,to:260,label:'冻结输入'},{from:270,to:380,label:'渲染候选'},{from:390,to:565,label:'验收交付'}],messages:steps.map(([from,to,label,variant='default'],i)=>({id:'step-'+(i+1),from,to,label,variant,y:160+i*30})),activations:[{participant:'cli',from:160,to:555,type:'backend'},{participant:'renderer',from:280,to:375,type:'backend'},{participant:'checker',from:400,to:465,type:'security'}],cards:[card('阅读方式','从上向下是顺序；箭头是进程与文件系统的交互。'),card('范围','呈现成功分支；哈希计算、清理细节按阅读粒度合并。')]};
const dn=(id,label,sublabel,stage,row,type='database')=>({id,label,sublabel,stage,row,type});
const dataflow={schema_version:1,diagram_type:'dataflow',meta:{...meta('Archify：JSON 如何成为网页'),viewBox:[1080,520]},stages:['输入','冻结','校验','生成','交付'].map(label=>({label})),nodes:[dn('json','图规格','节点与关系',0,1),dn('snapshot','输入快照','固定字节',1,1),dn('ir','已校验规格','渲染器内存',2,1,'backend'),dn('candidate','候选网页','私有目录',3,1),dn('html','最终网页','嵌入 SVG',4,1),dn('git','Git 证据','可选版本核验',1,2,'security'),dn('template','模板资源','样式与脚本',3,0),dn('receipt','交付回执','检查与哈希',3,2),dn('export','导出文件','图片与视频',4,2)],flows:[edge('json','snapshot'),edge('snapshot','ir'),edge('ir','candidate'),edge('candidate','html'),edge('git','ir',{variant:'security',fromSide:'right',toSide:'bottom'}),edge('template','candidate',{fromSide:'bottom',toSide:'top',route:'straight'}),edge('candidate','receipt',{fromSide:'bottom',toSide:'top',route:'straight'}),edge('html','export',{fromSide:'bottom',toSide:'top',route:'straight'})],cards:[card('数据不是源码自动抽取','JSON 已包含作者声明的关系；IR 是校验后的图规格。'),card('两类输出','命令交付 HTML 与回执；浏览器再将图形导出为媒体。')]};
const sn=(id,type,label,sublabel,lane,col,tag)=>({id,type,label,sublabel,lane,col,tag});
const lifecycle={schema_version:1,diagram_type:'lifecycle',meta:{...meta('Archify：候选产物的生命周期'),viewBox:[1030,566]},lanes:[{id:'main',label:'正常交付阶段'},{id:'errors',label:'提交前失败'},{id:'terminal',label:'失败结束'}],states:[sn('snapshot','start','准备快照','冻结输入','main',0,'01'),sn('render','active','渲染候选','私有文件','main',1,'02'),sn('check','decision','检查产物','验收门槛','main',2,'03'),sn('commit','active','原子提交','文件替换','main',3,'04'),sn('done','success','交付完成','回执输出','main',4,'05'),sn('invalid','failure','渲染失败','规格或布局','errors',0,'清理'),sn('bad','failure','检查失败','产物不合格','errors',1,'清理'),sn('io','failure','提交失败','文件操作','errors',2,'清理'),sn('end','failure','失败结束','旧文件仍保留','terminal',1,'未交付')],transitions:[edge('render','invalid',{variant:'security',fromSide:'bottom',toSide:'top',route:'straight'}),edge('check','bad',{variant:'security',route:'drop'}),edge('commit','io',{variant:'security',route:'drop'}),edge('invalid','end',{variant:'security',route:'drop'}),edge('bad','end',{variant:'security',fromSide:'bottom',toSide:'top',route:'straight'}),edge('io','end',{variant:'security',route:'drop'})],cards:[card('这是一张源码阶段抽象图','对应 deliver 控制分支；这些中文阶段不是源码里的状态枚举。'),card('交付边界','替换前失败会清理候选并保留已有文件；首次失败则没有新产物。','rose')]};
const base={schema_version:1,diagram_type:'architecture',meta:{...meta('字体依赖：变更前'),repository:{url:'https://github.com/tt-a1i/archify',revision:before}},components:[{id:'template',type:'backend',label:'查看器模板',sublabel:'声明在线字体',pos:[40,80],size:[220,88],sources:[source('assets/template.html',34,44,'变更前的 Google Fonts 链接')]},{id:'font',type:'cloud',label:'Google Fonts',sublabel:'浏览器请求在线字体',pos:[360,80],size:[220,88]},{id:'viewer',type:'frontend',label:'浏览器查看器',sublabel:'显示交付图形',pos:[680,80],size:[220,88]}],connections:[edge('template','viewer',{fromSide:'bottom',toSide:'bottom'}),edge('font','viewer')],cards:[card('真实历史变更','对照前一提交；字体加载采用异步在线样式表。')]};
const head=structuredClone(base);head.meta={...head.meta,title:'字体依赖：变更后',repository:{url:'https://github.com/tt-a1i/archify',revision}};head.components[0].sublabel='嵌入 WOFF2 字节';head.components[0].sources=[source('assets/template.html',34,55,'变更后的内嵌字体样式')];head.components[1]={id:'embedded',type:'database',label:'内嵌字体资源',sublabel:'JetBrains Mono 子集',pos:[360,80],size:[220,88],sources:[source('assets/JetBrainsMono-OFL.txt',1,20,'随包发布的字体许可证')]};head.connections=[edge('template','viewer',{fromSide:'bottom',toSide:'bottom'}),edge('embedded','viewer')];head.cards=[card('变更后的效果','字体覆盖字符不再依赖在线下载；中文仍使用系统字体回退。')];
function portable(v){if(Array.isArray(v))return v.map(portable);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,portable(x)]));if(typeof v==='string')return v.replaceAll(project,'projects/003-archify').replaceAll(upstream,'.research/archify');return v;}
function write(file,obj){fs.writeFileSync(path.join(web,file),JSON.stringify(obj,null,2)+'\n');}
function run(args){const r=spawnSync(process.execPath,[path.join(upstream,'archify/bin/archify.mjs'),...args],{encoding:'utf8',maxBuffer:20e6});if(r.status!==0)throw Error(r.stdout+r.stderr);return portable(JSON.parse(r.stdout));}
dataflow.flows.forEach((flow,i)=>{flow.label=['原始字节','图对象','SVG 与元数据','验收通过','行号结果','页面资源','检查与哈希','浏览器导出'][i];});
Object.assign(dataflow.flows[4],{via:[[530,385]],labelAt:[430,372]});
dataflow.flows[5].labelAt=[745,214];dataflow.flows[6].labelAt=[745,328];dataflow.flows[7].labelAt=[960,328];
lifecycle.meta.viewBox[1]=630;lifecycle.transitions[0].route='drop';
workflow.meta.legend={mode:'auto',entries:{backend:{label:'程序步骤'},database:{label:'交付回执'},security:{label:'产物检查'},external:{label:'用户 / Agent'}}};
dataflow.meta.legend={mode:'auto',entries:{security:{label:'证据核验'},database:{label:'数据与产物'},default:{label:'数据流'}}};
workflow.meta.views=[view('success','① 成功交付',['input','freeze','render','check','commit','receipt'],'沿职责泳道跟踪规格的准备、生成、验收与交付。'),view('repair','② 失败后修复',['render','check','repair','input'],'渲染或检查失败返回作者；修复与重试由外部执行。')];
sequence.meta.views=[view('prepare','① 准备输入',['author','cli','disk'],'调用者提交规格，主进程冻结本次输入字节。'),view('verify','② 子进程验收',['cli','disk','renderer','checker'],'渲染器写候选文件，检查器读取并验收。')];
dataflow.meta.views=[view('main','① 主数据路径',['json','snapshot','ir','candidate','html'],'关注图规格从输入到最终网页的形态变化。'),view('side','② 资源与输出',['git','ir','template','candidate','receipt','html','export'],'区分可选仓库证据、模板资源、交付回执与浏览器导出。')];
lifecycle.meta.views=[view('success','① 正常阶段',['snapshot','render','check','commit','done'],'候选产物逐步通过验收并成为最终文件。'),view('failure','② 提交前失败',['render','check','commit','invalid','bad','io','end'],'失败结束会清理候选，保留已有的最终文件。')];
base.meta.views=[view('font','字体依赖',['template','font','viewer'],'变更前，浏览器通过在线样式表请求字体。')];
head.meta.views=[view('font','字体依赖',['template','embedded','viewer'],'变更后，字体字节随查看器 HTML 一起交付。')];
const specs={architecture,workflow,sequence,dataflow,lifecycle};
for(const [type,spec]of Object.entries(specs)){const id='self-'+type;write('specs/'+id+'.json',spec);const receipt=run(['deliver',type,path.join(web,'specs/'+id+'.json'),path.join(web,'diagrams/'+id+'.html'),...(type==='architecture'?['--repo-root',upstream]:[]),'--quality','showcase','--json']);write('receipts/'+id+'.json',receipt);console.log(id+': delivered');}
write('specs/self-delta-base.json',base);write('specs/self-delta-head.json',head);
const delta=run(['compare','architecture',path.join(web,'specs/self-delta-base.json'),path.join(web,'specs/self-delta-head.json'),path.join(web,'diagrams/self-delta.html'),'--repo-root',upstream,'--receipt',path.join(web,'diagrams/self-delta.receipt.json'),'--quality','showcase','--json']);write('receipts/self-delta.json',delta);console.log('self-delta: compared');
write('receipts/self-provenance.json',{repository:'https://github.com/tt-a1i/archify',revision,before,scope:'Five Chinese source-derived diagrams, plus authored snapshots of the real font dependency change. Relationships are authored from code, not automatically extracted. Both delta snapshots use the pinned current renderer.',evidence:sources});



