const {chromium}=require('playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const {createHash}=require('node:crypto');
const web=path.resolve(__dirname,'../web');const base=process.env.ARCHIFY_DEMO_URL||'http://127.0.0.1:8763/';
(async()=>{fs.mkdirSync(path.join(web,'downloads'),{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const result={diagrams:[],styles:[],exports:[],errors};
try{
for(const type of ['architecture','workflow','sequence','dataflow','lifecycle','delta']){await page.goto(base+'diagrams/self-'+type+'.html?theme=light');await page.evaluate(()=>document.fonts.ready);await page.locator('svg').first().waitFor();await page.screenshot({path:path.join(web,'assets/self-'+type+'-full.png'),fullPage:true});if(type!=='delta')await page.locator('.diagram-container').screenshot({path:path.join(web,'assets/self-'+type+'-preview.png')});else await page.screenshot({path:path.join(web,'assets/self-delta-preview.png'),fullPage:true});result.diagrams.push({type,title:await page.title()});}
await page.goto(base+'diagrams/self-architecture.html?theme=light');
await page.locator('#node-cli').click();const source=page.locator('a.semantic-passport-source').first();await source.waitFor();result.sourceHref=await source.getAttribute('href');assert.ok(result.sourceHref.includes('/10722002bb8777ecb639d93c49586fae4adf3ae4/archify/bin/archify.mjs#L821-L966'));await page.screenshot({path:path.join(web,'assets/self-source.png'),fullPage:true});
await page.goto(base+'diagrams/self-architecture.html?theme=light#focus=cli&reach=downstream');await page.locator('[data-reach-origin]').waitFor();result.downstream=await page.locator('.diagram-container > svg [data-reach-match][data-node-id]').evaluateAll(es=>es.map(e=>e.dataset.nodeId));assert.ok(result.downstream.includes('viewer'));await page.screenshot({path:path.join(web,'assets/self-reach.png'),fullPage:true});
async function download(selector,name){const [d]=await Promise.all([page.waitForEvent('download',{timeout:60000}),page.evaluate(selector=>{if(selector.includes('reach-share'))return Archify.exportMenu.downloadReachShareCard();if(selector.includes('route-share'))return Archify.exportMenu.downloadRouteShareCard();return Archify.exportMenu.run(document.querySelector(selector).dataset.format);},selector)]);const target=path.join(web,'downloads',name);await d.saveAs(target);const b=fs.readFileSync(target);assert.ok(b.length>1000);const ext=path.extname(name);if(ext==='.png')assert.equal(b.subarray(0,8).toString('hex'),'89504e470d0a1a0a');if(ext==='.jpg')assert.equal(b.subarray(0,2).toString('hex'),'ffd8');if(ext==='.webp')assert.equal(b.subarray(8,12).toString(),'WEBP');if(ext==='.webm')assert.equal(b.subarray(0,4).toString('hex'),'1a45dfa3');if(ext==='.svg')assert.ok(b.toString().includes('<svg'));result.exports.push({name,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')});console.log('export '+name);}
await download('[data-action="reach-share-card"]','archify-reach.png');
await page.goto(base+'diagrams/self-architecture.html?theme=light#route=spec~viewer');await page.locator('[data-action="route-share-card"]').waitFor({state:'attached'});await download('[data-action="route-share-card"]','archify-route.png');result.route=await page.evaluate(()=>Archify.routeProbe.exportSnapshot());assert.ok(result.route);
await page.goto(base+'diagrams/self-architecture.html?theme=light');
for(const [format,name]of [['png','archify.png'],['jpeg','archify.jpg'],['webp','archify.webp'],['svg','archify.svg'],['share-card','archify-share.png'],['webm','archify.webm']])await download('[data-format="'+format+'"]',name);
for(const theme of ['light','dark']){await page.goto(base+'diagrams/self-architecture.html?theme='+theme);for(let i=0;i<4;i++){const preset=await page.locator('html').getAttribute('data-preset');await page.locator('.diagram-container').screenshot({path:path.join(web,'assets/self-style-'+preset+'-'+theme+'.png')});result.styles.push({theme,preset});await page.keyboard.press('s');}}
assert.equal(errors.length,0,JSON.stringify(errors));result.ok=true;result.exportMethod='Invoked original Archify.exportMenu methods in Chrome; unmodified native export implementation. Toolbar interaction clears focus in this version; saved route/reach files use native methods.';fs.writeFileSync(path.join(web,'receipts/self-browser.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});



