const steps = [
['用户 → 平台','先创建一个共同的工作目标','用户创建 Issue 并分配给小队。平台记录目标和负责人，为组长创建一次 Run。','任务：修复登录失败，补回归测试，交付可评审的变更。','直接分配给单个 Agent 时，可以跳过组长协调。'],
['组长 Agent → 平台','组长选择合适的成员','组长读取任务、成员名单、职责和 Skills，通过 Multica CLI/API 发布委派评论。分工判断由模型完成。','[@开发](mention://agent/成员UUID)\n请处理登录问题，补回归测试，反馈分支或 PR 位置。','结构化 ID 确定接收者，自然语言描述具体工作。普通 @名字 不等价。'],
['平台 → Daemon → 成员','把一条委派变成真实执行','平台解析提及，检查权限和触发条件，把成员 Run 放入队列。对应执行机器领取，再由适配层启动 Agent 工具。','排队 → 领取 → 准备工作目录与配置 → 启动 Agent','组长记录决策后结束本轮。平台的路由与队列不依赖组长持续等待。'],
['成员 → 任务记录','独立工作，留下可交接结果','成员使用自己的 Agent 工具、模型与执行环境处理任务，并通过评论回传结果和明确的产物位置。','已修复。回归测试通过，变更在 demo/login-fix 分支。\n请使用该分支继续验证。','共享任务和讨论记录；跨机器代码需分支、PR、附件等明确交接。'],
['评论事件 → 组长','反馈到达，再次启动组长','平台按触发规则为组长创建后续 Run。组长读取最新活动，决定下一步，并将决策写入任务。','[@测试](mention://agent/测试UUID)\n请验证 demo/login-fix，重点检查错误密码和空输入。','已有待执行组长任务时会去重；无须采取行动时，组长记录 no_action 并结束。'],
['组长 → 人工评审','检查整体目标，交付给人','组长确认整体目标满足后，将其负责的任务转到待评审。人检查真实产物与验收标准；不通过则通过评论要求返工。','开发完成 + 测试反馈 + 产物证据 → 待评审','Run completed 不等于验收通过；待评审不等于强制审批。评论可触发后续工作，要即时制止应停止 Run。']
]; let current=0;const buttons=[...document.querySelectorAll('[data-step]')];function show(i){current=i;const s=steps[i];['owner','title','body','message','boundary'].forEach((k,n)=>document.getElementById('step-'+k).textContent=s[n]);buttons.forEach((b,n)=>{b.classList.toggle('active',n===i);b.setAttribute('aria-pressed',String(n===i))});document.getElementById('next-step').textContent=i===5?'重新查看 →':'下一步 →'}buttons.forEach(b=>b.addEventListener('click',()=>show(Number(b.dataset.step))));document.getElementById('next-step').addEventListener('click',()=>show((current+1)%steps.length));show(0);
fetch('verification.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(v=>{const box=document.getElementById('verification');box.textContent='';const strong=document.createElement('strong');strong.textContent=v.title;box.append(strong);const ul=document.createElement('ul');v.checks.forEach(c=>{const li=document.createElement('li');li.textContent=c;ul.append(li)});box.append(ul);v.screenshots.forEach(s=>{const f=document.createElement('figure');const a=document.createElement('a');a.href=s.file;a.target='_blank';const im=document.createElement('img');im.src=s.file;im.alt=s.caption;im.loading='lazy';a.append(im);const cap=document.createElement('figcaption');cap.textContent=s.caption;f.append(a,cap);document.getElementById('screenshots').append(f)})}).catch(()=>{document.getElementById('verification').textContent='请参阅随项目保存的 verification.md，查看具体运行范围。'});
