'use strict';
const tasks = {
  scrape: {title:'读一篇文章',scope:'核心 API',desc:'提供一个确切页面，读取它的主要内容。抓首页不会自动得到整个网站。',input:'https://example.com/news/tool-update\n\n要求：主要内容，Markdown',output:'# 示例工具发布 2.0\n\n新增代码搜索与项目问答。\n目前面向 Pro 用户开放。',flow:['接收网址','选择可用抓取引擎','提取主要内容','转换并返回'],limit:'这是虚构文章的输出示意。正文获取可能遗漏内容；成功返回也需要检查目标页面状态。',endpoint:'POST /v2/scrape',request:{url:'https://example.com/news/tool-update',formats:['markdown'],onlyMainContent:true,maxAge:0},source:'https://docs.firecrawl.dev/features/scrape'},
  search: {title:'先找，再读',scope:'核心 API',desc:'不知道文章地址也可以使用：输入关键词，先找候选网页，再读取结果内容。',input:'AI 编程工具 新版本\n\n最多 5 个结果，同时获取正文',output:'候选结果示意\n1. 工具 A 更新说明 + 来源 URL + 正文\n2. 工具 B 发布公告 + 来源 URL + 正文\n…',flow:['执行搜索','取得候选网址','按要求抓取结果页','返回来源与内容'],limit:'搜索结果受索引和查询影响，不保证完整覆盖，也不保证每个候选页面都能成功抓取。',endpoint:'POST /v2/search',request:{query:'AI 编程工具 新版本',limit:5,scrapeOptions:{formats:['markdown']}},source:'https://docs.firecrawl.dev/features/search'},
  map: {title:'找到站内页面',scope:'核心 API',desc:'先拿到站内的网址清单，再决定哪些值得读取。Map 本身不等于抓完全文。',input:'https://example.com\n\n查找主题：pricing',output:'候选网址示意\nhttps://example.com/pricing\nhttps://example.com/enterprise\nhttps://example.com/faq/billing',flow:['读取 Sitemap 等线索','补充其他发现路径','按主题关联排序','返回网址列表'],limit:'主要利用 Sitemap，并可结合搜索和历史爬取数据。优先速度，可能漏掉页面。',endpoint:'POST /v2/map',request:{url:'https://example.com',search:'pricing'},source:'https://docs.firecrawl.dev/features/map'},
  crawl: {title:'收集网站文档',scope:'核心 API · 异步任务',desc:'给定网站入口与范围，服务会发现链接并组织多个页面的抓取。',input:'https://example.com/docs\n\n最多 100 页，返回 Markdown',output:'先返回任务 ID\n→ 查询执行进度\n→ 获取多个页面的正文和来源\n→ 单独检查失败记录',flow:['发现初始网址','按范围过滤链接','排队与并发抓取','发现新链接继续执行'],limit:'受数量、范围、发现深度和目标网站影响。任务结果要及时保存；实际可用性依部署而异。',endpoint:'POST /v2/crawl',request:{url:'https://example.com/docs',limit:100,scrapeOptions:{formats:['markdown']}},source:'https://docs.firecrawl.dev/features/crawl'},
  batch: {title:'读取一批网址',scope:'批量 API · 异步任务',desc:'你已经确定网址列表时，一次提交给服务处理，不需要从网站入口继续发现。',input:'https://example.com/news/a\nhttps://example.com/news/b\nhttps://example.com/news/c',output:'先返回任务 ID\n完成后获得多个文档：\n{ 来源, 正文, 页面状态 }\n每个页面仍可能独立失败',flow:['接收网址列表','建立批量任务','并发读取页面','查询并保存结果'],limit:'Batch 处理给定列表；Crawl 则包含发现更多页面的步骤。SDK 可提供等待任务完成的便捷方法。',endpoint:'POST /v2/batch/scrape',request:{urls:['https://example.com/news/a','https://example.com/news/b'],formats:['markdown']},source:'https://docs.firecrawl.dev/features/batch-scrape'},
  json: {title:'整理为业务字段',scope:'需配置模型能力',desc:'把正文按你的字段要求整理为结构化数据。语义提取与网页获取是两个环节。',input:'https://example.com/product\n\n提取：名称、价格、计费条件、是否开源',output:'{\n  "name": "示例工具",\n  "monthly_price": 20,\n  "billing": "按年支付",\n  "open_source": null\n}',flow:['获取页面内容','转换成模型可读文本','模型按字段提取','返回 JSON'],limit:'示意价格不是实际报价。缺失字段应返回 null；字段结构正确不等于事实正确。HTML 属性可能在转换中丢失。',endpoint:'POST /v2/scrape',request:{url:'https://example.com/product',formats:[{type:'json',prompt:'提取产品名称和是否开源。页面没写的信息返回 null。',schema:{type:'object',properties:{name:{type:['string','null']},open_source:{type:['boolean','null']}}}}]},source:'https://docs.firecrawl.dev/features/llm-extract'},
  interact: {title:'操作页面后读取',scope:'云服务 · 默认自部署不包含',desc:'使用抓取返回的会话标识，继续输入、点击或导航，访问需要交互才能出现的内容。',input:'先抓取页面取得 scrapeId\n\n然后：在搜索框搜索“代码助手”',output:'操作结果示意\n页面进入搜索结果\n返回执行结果；可继续交互\n具体输出依接口和操作而异',flow:['建立或接续会话','提交操作指令','浏览器执行','返回结果或继续操作'],limit:'Interact 与一次抓取中的 Actions 有区别；可用操作依服务能力而定。此页没有远程浏览器会话。',endpoint:'POST /v2/scrape/{scrapeId}/interact',request:{prompt:'在网站的搜索框搜索“代码助手”'},source:'https://github.com/firecrawl/firecrawl#interact'},
  agent: {title:'描述采集目标',scope:'云服务 · 默认自部署不包含',desc:'直接说明需要什么数据，由 Agent 组织搜索、导航与获取。可选提供网址或结果字段。',input:'找出示例公司 A 与 B 的套餐，\n比较价格和限制，并给出来源。',output:'结果示意\n公司 A：套餐与限制 + 来源\n公司 B：套餐与限制 + 来源\n缺失信息：明确标注未知',flow:['理解任务目标','规划并寻找来源','导航和采集','整理带来源的结果'],limit:'此处展示任务形式，不是已执行结果。模型规划仍受来源覆盖、预算和页面可访问性影响。',endpoint:'POST /v2/agent',request:{prompt:'比较示例公司 A 与 B 的收费套餐与限制，并给出来源。'},source:'https://docs.firecrawl.dev/features/agent'}
};
const routes = {
 import:{label:'业务系统的导入路径',title:'读取用户导出的文件',description:'用户从来源平台导出 JSON、CSV 或 HTML，业务程序解析后入库。导入过程本身不需要浏览器。',flow:['来源平台提供导出文件','用户交给自己的程序','解析字段并校验格式','保存、分类和检索'],conclusion:'这是一种补充数据入口，不是 Firecrawl 默认提供的通用账号导入器。数据范围取决于平台导出内容。'},
 extension:{label:'使用现有浏览器',title:'扩展读取用户已经打开的页面',description:'用户自行打开、登录页面，扩展在获得权限后读取页面内容。读取页面不一定需要自动点击。',flow:['用户安装并授权扩展','打开来源页面','扩展读取已加载内容','经授权保存到自己的系统'],conclusion:'需要另行开发或选择扩展。Firecrawl 不会自动继承本机登录；扩展也不会豁免来源平台规则。'},
 webhook:{label:'由来源发起通知',title:'有更新时，网站主动推送',description:'来源平台支持 Webhook 时，可在事件发生后向你配置的接收地址发送数据，不必反复轮询。',flow:['来源支持并配置事件通知','来源发生新事件','来源向你的服务发送数据','业务系统校验、去重并处理'],conclusion:'这是来源平台的数据入口；Firecrawl 自己的任务完成 Webhook 是采集任务通知，不能让任意网站主动推送。'},
 html:{label:'普通网络请求',title:'网页正文已经在 HTML 中',description:'目标网站直接返回包含正文的网页代码，HTTP 客户端就能取得内容，不必为每次请求都启动浏览器。',flow:['你的程序调用 Firecrawl API','HTTP 客户端请求文章 URL','目标网站返回 HTML','解析正文并转换输出'],conclusion:'数据来源：目标网页的 HTML。Firecrawl API 是你使用服务的入口。'},
 browser:{label:'动态页面路径',title:'控制真实无头浏览器，让内容加载出来',description:'服务器初始可能只返回“正在加载”。浏览器执行 JavaScript，页面脚本再请求数据，最后将正文显示在页面结构中。',flow:['Firecrawl 选择浏览器引擎','访问网址并执行页面脚本','脚本可能请求网站内部接口','读取加载后的页面内容'],conclusion:'无头是没有可见窗口，仍是真实浏览器引擎。加载、渲染和点击是不同动作；读取页面通常不需要截图识字。'},
 rss:{label:'订阅源路径',title:'RSS 提供更新条目或全文',description:'新闻程序读取 RSS，可以得到标题、链接、摘要，有时也包括全文。RSS 不是 Firecrawl 普通网页抓取的主要机制。',flow:['新闻程序请求 RSS 地址','解析更新条目','若只有摘要，取得文章 URL','可交给 Firecrawl 补充正文'],conclusion:'RSS 与网页抓取可以配合使用。RSS 已提供足够内容时，无需重复抓取。'},
 api:{label:'平台接口路径',title:'程序直接获取结构化数据',description:'GitHub 等平台提供接口，程序按照接口规定请求 Issue、Release 等数据。Agents Radar 为不同平台编写了这样的适配。',flow:['程序调用目标平台 API','平台返回 JSON 等结构化响应','程序读取标题、正文与状态','直接进入筛选和分析'],conclusion:'调用 Firecrawl API ≠ 调用目标网站官方 API。普通网页抓取不自动成为官方 API 集成。'}
};
function text(id,value){document.getElementById(id).textContent=value;}
function list(id,items){document.getElementById(id).replaceChildren(...items.map(value=>{const li=document.createElement('li');li.textContent=value;return li;}));}
function selectTask(key){const t=tasks[key];if(!t)return;document.querySelectorAll('[data-task]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.task===key)));text('task-title',t.title);text('task-scope',t.scope);text('task-desc',t.desc);text('task-input',t.input);text('task-output',t.output);list('task-flow',t.flow);text('task-limit',t.limit);text('task-endpoint',t.endpoint);text('task-request',JSON.stringify(t.request,null,2));document.getElementById('task-source').href=t.source;}
function selectRoute(key){const r=routes[key];if(!r)return;document.querySelectorAll('[data-route]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.route===key)));text('route-label',r.label);text('route-title',r.title);text('route-description',r.description);list('route-flow',r.flow);text('route-conclusion',r.conclusion);}
document.querySelectorAll('[data-task]').forEach(b=>b.addEventListener('click',()=>selectTask(b.dataset.task)));
document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>selectRoute(b.dataset.route)));
selectTask('scrape');selectRoute('html');
